name: kisah_nabi
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.7.0
  hexcolor: ^3.0.1
  google_fonts: ^4.0.4
  cached_network_image: ^3.2.3
  drop_down_list: ^0.0.5
  auto_size_text: ^3.0.0
  get_storage: ^2.1.1
  flutter_svg: ^2.0.7
  pod_player: ^0.2.1
  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.0
  url_launcher: ^6.1.12

dev_dependencies: 
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ic_launcher.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter: 
  uses-material-design: true

  assets:
    - assets/

